# encoding: utf-8
import uuid

from EtikTakApp.util import util
from EtikTakApp.models.users import MobileNumber

from django.db import models
from datetime import datetime

class Client(models.Model):
    uid = models.CharField(max_length=255)
    created_timestamp = models.DateTimeField()

    def create_client(self):
        """
        Creates and saves a client with autogenerated UID.
        """
        client = Client(uid = uuid.uuid4(), created_timestamp = datetime.now())
        client.save()
        return client

    def __unicode__(self):
        return u"%s" % self.uid

    class Meta:
        verbose_name = u"Klient"
        verbose_name_plural = u"Klienter"
        app_label = "EtikTakApp"

class ClientKey(models.Model):
    uid = models.CharField(max_length=255) # EncryptedCharField(max_length=255)
    mobile_number_hash_password_hash_hashed = models.CharField(max_length=255) # EncryptedCharField(max_length=255)
    challenge_hash = models.CharField(max_length=255) # EncryptedCharField(max_length=255)
    created_timestamp = models.DateTimeField()

    @staticmethod
    def create_client_key(mobile_number, password):
        """
        Creates and saves a client key with autogenerated UID and with a hash of
        the sum of the specified mobile number hashed concatenated with the specified
        password hashed. Challenge is left empty.
        """
        if MobileNumber.objects.exists(mobile_number):
            raise ValueError("Mobile number %s already exists" % mobile_number)
        client_key = ClientKey(
            uid = uuid.uuid4(),
            mobile_number_hash_password_hash_hashed = util.sha256(util.sha256(mobile_number) + util.sha256(password)),
            created_timestamp = datetime.now())
        client_key.save()
        return client_key

    def __unicode__(self):
        return u"%s | %s | %s" % (self.uid, self.mobile_number_hash_password_hash_hashed, self.challenge_hash)

    class Meta:
        verbose_name = u"Klientnøgle"
        verbose_name_plural = u"Klientnøgler"
        app_label = "EtikTakApp"

